// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: tkv_proxy.proto

package proxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TxnProxyService_BeginTxn_FullMethodName = "/juicefs.proxy.v1.TxnProxyService/BeginTxn"
	TxnProxyService_Get_FullMethodName      = "/juicefs.proxy.v1.TxnProxyService/Get"
	TxnProxyService_BatchGet_FullMethodName = "/juicefs.proxy.v1.TxnProxyService/BatchGet"
	TxnProxyService_Scan_FullMethodName     = "/juicefs.proxy.v1.TxnProxyService/Scan"
	TxnProxyService_Commit_FullMethodName   = "/juicefs.proxy.v1.TxnProxyService/Commit"
	TxnProxyService_Rollback_FullMethodName = "/juicefs.proxy.v1.TxnProxyService/Rollback"
)

// TxnProxyServiceClient is the client API for TxnProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TiKV Proxy Service
type TxnProxyServiceClient interface {
	// Begin a new transaction
	BeginTxn(ctx context.Context, in *BeginTxnRequest, opts ...grpc.CallOption) (*BeginTxnResponse, error)
	// Get a single key
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// BatchGet multiple keys with streaming response
	BatchGet(ctx context.Context, in *BatchGetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BatchGetResponse], error)
	// Scan keys with streaming response
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanResponse], error)
	// Commit transaction
	Commit(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CommitRequest, CommitResponse], error)
	// Rollback transaction
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
}

type txnProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTxnProxyServiceClient(cc grpc.ClientConnInterface) TxnProxyServiceClient {
	return &txnProxyServiceClient{cc}
}

func (c *txnProxyServiceClient) BeginTxn(ctx context.Context, in *BeginTxnRequest, opts ...grpc.CallOption) (*BeginTxnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginTxnResponse)
	err := c.cc.Invoke(ctx, TxnProxyService_BeginTxn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txnProxyServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, TxnProxyService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txnProxyServiceClient) BatchGet(ctx context.Context, in *BatchGetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BatchGetResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TxnProxyService_ServiceDesc.Streams[0], TxnProxyService_BatchGet_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchGetRequest, BatchGetResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TxnProxyService_BatchGetClient = grpc.ServerStreamingClient[BatchGetResponse]

func (c *txnProxyServiceClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TxnProxyService_ServiceDesc.Streams[1], TxnProxyService_Scan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanRequest, ScanResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TxnProxyService_ScanClient = grpc.ServerStreamingClient[ScanResponse]

func (c *txnProxyServiceClient) Commit(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CommitRequest, CommitResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TxnProxyService_ServiceDesc.Streams[2], TxnProxyService_Commit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommitRequest, CommitResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TxnProxyService_CommitClient = grpc.ClientStreamingClient[CommitRequest, CommitResponse]

func (c *txnProxyServiceClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, TxnProxyService_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TxnProxyServiceServer is the server API for TxnProxyService service.
// All implementations must embed UnimplementedTxnProxyServiceServer
// for forward compatibility.
//
// TiKV Proxy Service
type TxnProxyServiceServer interface {
	// Begin a new transaction
	BeginTxn(context.Context, *BeginTxnRequest) (*BeginTxnResponse, error)
	// Get a single key
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// BatchGet multiple keys with streaming response
	BatchGet(*BatchGetRequest, grpc.ServerStreamingServer[BatchGetResponse]) error
	// Scan keys with streaming response
	Scan(*ScanRequest, grpc.ServerStreamingServer[ScanResponse]) error
	// Commit transaction
	Commit(grpc.ClientStreamingServer[CommitRequest, CommitResponse]) error
	// Rollback transaction
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	mustEmbedUnimplementedTxnProxyServiceServer()
}

// UnimplementedTxnProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTxnProxyServiceServer struct{}

func (UnimplementedTxnProxyServiceServer) BeginTxn(context.Context, *BeginTxnRequest) (*BeginTxnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginTxn not implemented")
}
func (UnimplementedTxnProxyServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTxnProxyServiceServer) BatchGet(*BatchGetRequest, grpc.ServerStreamingServer[BatchGetResponse]) error {
	return status.Errorf(codes.Unimplemented, "method BatchGet not implemented")
}
func (UnimplementedTxnProxyServiceServer) Scan(*ScanRequest, grpc.ServerStreamingServer[ScanResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedTxnProxyServiceServer) Commit(grpc.ClientStreamingServer[CommitRequest, CommitResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedTxnProxyServiceServer) Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedTxnProxyServiceServer) mustEmbedUnimplementedTxnProxyServiceServer() {}
func (UnimplementedTxnProxyServiceServer) testEmbeddedByValue()                         {}

// UnsafeTxnProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TxnProxyServiceServer will
// result in compilation errors.
type UnsafeTxnProxyServiceServer interface {
	mustEmbedUnimplementedTxnProxyServiceServer()
}

func RegisterTxnProxyServiceServer(s grpc.ServiceRegistrar, srv TxnProxyServiceServer) {
	// If the following call pancis, it indicates UnimplementedTxnProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TxnProxyService_ServiceDesc, srv)
}

func _TxnProxyService_BeginTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxnProxyServiceServer).BeginTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TxnProxyService_BeginTxn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxnProxyServiceServer).BeginTxn(ctx, req.(*BeginTxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxnProxyService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxnProxyServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TxnProxyService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxnProxyServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxnProxyService_BatchGet_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BatchGetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TxnProxyServiceServer).BatchGet(m, &grpc.GenericServerStream[BatchGetRequest, BatchGetResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TxnProxyService_BatchGetServer = grpc.ServerStreamingServer[BatchGetResponse]

func _TxnProxyService_Scan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TxnProxyServiceServer).Scan(m, &grpc.GenericServerStream[ScanRequest, ScanResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TxnProxyService_ScanServer = grpc.ServerStreamingServer[ScanResponse]

func _TxnProxyService_Commit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TxnProxyServiceServer).Commit(&grpc.GenericServerStream[CommitRequest, CommitResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TxnProxyService_CommitServer = grpc.ClientStreamingServer[CommitRequest, CommitResponse]

func _TxnProxyService_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxnProxyServiceServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TxnProxyService_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxnProxyServiceServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TxnProxyService_ServiceDesc is the grpc.ServiceDesc for TxnProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TxnProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "juicefs.proxy.v1.TxnProxyService",
	HandlerType: (*TxnProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginTxn",
			Handler:    _TxnProxyService_BeginTxn_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TxnProxyService_Get_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _TxnProxyService_Rollback_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BatchGet",
			Handler:       _TxnProxyService_BatchGet_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Scan",
			Handler:       _TxnProxyService_Scan_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Commit",
			Handler:       _TxnProxyService_Commit_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "tkv_proxy.proto",
}
