// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: tkv_proxy.proto

package proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Get single key
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTs       uint64                 `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_tkv_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tkv_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_tkv_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTs       uint64                 `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_tkv_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tkv_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_tkv_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// BatchGet multiple keys (streaming response)
type BatchGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTs       uint64                 `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	Keys          [][]byte               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetRequest) Reset() {
	*x = BatchGetRequest{}
	mi := &file_tkv_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRequest) ProtoMessage() {}

func (x *BatchGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tkv_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRequest.ProtoReflect.Descriptor instead.
func (*BatchGetRequest) Descriptor() ([]byte, []int) {
	return file_tkv_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetRequest) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *BatchGetRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type BatchGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTs       uint64                 `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	Keys          [][]byte               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Values        [][]byte               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetResponse) Reset() {
	*x = BatchGetResponse{}
	mi := &file_tkv_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResponse) ProtoMessage() {}

func (x *BatchGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tkv_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResponse.ProtoReflect.Descriptor instead.
func (*BatchGetResponse) Descriptor() ([]byte, []int) {
	return file_tkv_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetResponse) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *BatchGetResponse) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *BatchGetResponse) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// Scan keys (streaming response)
type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTs       uint64                 `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	StartKey      []byte                 `protobuf:"bytes,2,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`  // Start key for scan
	EndKey        []byte                 `protobuf:"bytes,3,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`        // End key for scan (exclusive)
	ScanSize      int32                  `protobuf:"varint,4,opt,name=scan_size,json=scanSize,proto3" json:"scan_size,omitempty"` // Number of items to scan per stream response (default: 100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_tkv_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tkv_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_tkv_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *ScanRequest) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *ScanRequest) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *ScanRequest) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *ScanRequest) GetScanSize() int32 {
	if x != nil {
		return x.ScanSize
	}
	return 0
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTs       uint64                 `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	Keys          [][]byte               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Values        [][]byte               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_tkv_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tkv_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_tkv_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *ScanResponse) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *ScanResponse) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ScanResponse) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ScanResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

// Commit transaction
type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTs       uint64                 `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	Keys          [][]byte               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Values        [][]byte               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_tkv_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tkv_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_tkv_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *CommitRequest) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *CommitRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *CommitRequest) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitTs      uint64                 `protobuf:"varint,1,opt,name=commit_ts,json=commitTs,proto3" json:"commit_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_tkv_proxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tkv_proxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_tkv_proxy_proto_rawDescGZIP(), []int{7}
}

func (x *CommitResponse) GetCommitTs() uint64 {
	if x != nil {
		return x.CommitTs
	}
	return 0
}

var File_tkv_proxy_proto protoreflect.FileDescriptor

const file_tkv_proxy_proto_rawDesc = "" +
	"\n" +
	"\x0ftkv_proxy.proto\x12\x10juicefs.proxy.v1\"9\n" +
	"\n" +
	"GetRequest\x12\x19\n" +
	"\bstart_ts\x18\x01 \x01(\x04R\astartTs\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\">\n" +
	"\vGetResponse\x12\x19\n" +
	"\bstart_ts\x18\x01 \x01(\x04R\astartTs\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"@\n" +
	"\x0fBatchGetRequest\x12\x19\n" +
	"\bstart_ts\x18\x01 \x01(\x04R\astartTs\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\fR\x04keys\"Y\n" +
	"\x10BatchGetResponse\x12\x19\n" +
	"\bstart_ts\x18\x01 \x01(\x04R\astartTs\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\fR\x04keys\x12\x16\n" +
	"\x06values\x18\x03 \x03(\fR\x06values\"{\n" +
	"\vScanRequest\x12\x19\n" +
	"\bstart_ts\x18\x01 \x01(\x04R\astartTs\x12\x1b\n" +
	"\tstart_key\x18\x02 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x03 \x01(\fR\x06endKey\x12\x1b\n" +
	"\tscan_size\x18\x04 \x01(\x05R\bscanSize\"g\n" +
	"\fScanResponse\x12\x19\n" +
	"\bstart_ts\x18\x01 \x01(\x04R\astartTs\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\fR\x04keys\x12\x16\n" +
	"\x06values\x18\x03 \x03(\fR\x06values\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\"V\n" +
	"\rCommitRequest\x12\x19\n" +
	"\bstart_ts\x18\x01 \x01(\x04R\astartTs\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\fR\x04keys\x12\x16\n" +
	"\x06values\x18\x03 \x03(\fR\x06values\"-\n" +
	"\x0eCommitResponse\x12\x1b\n" +
	"\tcommit_ts\x18\x01 \x01(\x04R\bcommitTs2\xbc\x02\n" +
	"\x0fTxnProxyService\x12B\n" +
	"\x03Get\x12\x1c.juicefs.proxy.v1.GetRequest\x1a\x1d.juicefs.proxy.v1.GetResponse\x12Q\n" +
	"\bBatchGet\x12!.juicefs.proxy.v1.BatchGetRequest\x1a\".juicefs.proxy.v1.BatchGetResponse\x12E\n" +
	"\x04Scan\x12\x1d.juicefs.proxy.v1.ScanRequest\x1a\x1e.juicefs.proxy.v1.ScanResponse\x12K\n" +
	"\x06Commit\x12\x1f.juicefs.proxy.v1.CommitRequest\x1a .juicefs.proxy.v1.CommitResponseB1Z/github.com/juicedata/juicefs/pkg/proxy/v1;proxyb\x06proto3"

var (
	file_tkv_proxy_proto_rawDescOnce sync.Once
	file_tkv_proxy_proto_rawDescData []byte
)

func file_tkv_proxy_proto_rawDescGZIP() []byte {
	file_tkv_proxy_proto_rawDescOnce.Do(func() {
		file_tkv_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tkv_proxy_proto_rawDesc), len(file_tkv_proxy_proto_rawDesc)))
	})
	return file_tkv_proxy_proto_rawDescData
}

var file_tkv_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_tkv_proxy_proto_goTypes = []any{
	(*GetRequest)(nil),       // 0: juicefs.proxy.v1.GetRequest
	(*GetResponse)(nil),      // 1: juicefs.proxy.v1.GetResponse
	(*BatchGetRequest)(nil),  // 2: juicefs.proxy.v1.BatchGetRequest
	(*BatchGetResponse)(nil), // 3: juicefs.proxy.v1.BatchGetResponse
	(*ScanRequest)(nil),      // 4: juicefs.proxy.v1.ScanRequest
	(*ScanResponse)(nil),     // 5: juicefs.proxy.v1.ScanResponse
	(*CommitRequest)(nil),    // 6: juicefs.proxy.v1.CommitRequest
	(*CommitResponse)(nil),   // 7: juicefs.proxy.v1.CommitResponse
}
var file_tkv_proxy_proto_depIdxs = []int32{
	0, // 0: juicefs.proxy.v1.TxnProxyService.Get:input_type -> juicefs.proxy.v1.GetRequest
	2, // 1: juicefs.proxy.v1.TxnProxyService.BatchGet:input_type -> juicefs.proxy.v1.BatchGetRequest
	4, // 2: juicefs.proxy.v1.TxnProxyService.Scan:input_type -> juicefs.proxy.v1.ScanRequest
	6, // 3: juicefs.proxy.v1.TxnProxyService.Commit:input_type -> juicefs.proxy.v1.CommitRequest
	1, // 4: juicefs.proxy.v1.TxnProxyService.Get:output_type -> juicefs.proxy.v1.GetResponse
	3, // 5: juicefs.proxy.v1.TxnProxyService.BatchGet:output_type -> juicefs.proxy.v1.BatchGetResponse
	5, // 6: juicefs.proxy.v1.TxnProxyService.Scan:output_type -> juicefs.proxy.v1.ScanResponse
	7, // 7: juicefs.proxy.v1.TxnProxyService.Commit:output_type -> juicefs.proxy.v1.CommitResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tkv_proxy_proto_init() }
func file_tkv_proxy_proto_init() {
	if File_tkv_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tkv_proxy_proto_rawDesc), len(file_tkv_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tkv_proxy_proto_goTypes,
		DependencyIndexes: file_tkv_proxy_proto_depIdxs,
		MessageInfos:      file_tkv_proxy_proto_msgTypes,
	}.Build()
	File_tkv_proxy_proto = out.File
	file_tkv_proxy_proto_goTypes = nil
	file_tkv_proxy_proto_depIdxs = nil
}
