syntax = "proto3";

package juicefs.proxy.v1;

option go_package = "github.com/juicedata/juicefs/pkg/proxy/v1;proxy";

// TiKV Proxy Service
service TxnProxyService {
    
    // Get a single key
    rpc Get(GetRequest) returns (GetResponse);
    
    // BatchGet multiple keys with streaming response
    rpc BatchGet(BatchGetRequest) returns (stream BatchGetResponse);
    
    // Scan keys with streaming response
    rpc Scan(ScanRequest) returns (stream ScanResponse);

    // Commit transaction
    rpc Commit(stream CommitRequest) returns (CommitResponse);
}


// Get single key
message GetRequest {
    uint64 start_ts = 1;
    bytes key = 2;
}

message GetResponse {
    uint64 start_ts = 1;
    bytes value = 2;
}

// BatchGet multiple keys (streaming response)
message BatchGetRequest {
    uint64 start_ts = 1;
    repeated bytes keys = 2;
}

message BatchGetResponse {
    uint64 start_ts = 1;
    repeated bytes keys = 2;
    repeated bytes values = 3;
}

// Scan keys (streaming response)
message ScanRequest {
    uint64 start_ts = 1;
    bytes start_key = 2;    // Start key for scan
    bytes end_key = 3;      // End key for scan (exclusive)
    int32 scan_size = 4;    // Number of items to scan per stream response (default: 100)   
}

message ScanResponse {
    uint64 start_ts = 1;
    repeated bytes keys = 2;
    repeated bytes values = 3;
}


// Commit transaction
message CommitRequest {
    uint64 start_ts = 1;
    repeated bytes keys = 2;
    repeated bytes values = 3;
    int32 total_keys = 4;
}

message CommitResponse {
    uint64 commit_ts = 1;
}
